
CREATE TABLE USERS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NICK VARCHAR(255) NOT NULL,
    MAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) ,
    IS_GOOGLE_USER BOOLEAN NOT NULL,
    GOOGLE_ID VARCHAR(255),
    DATE_CREATED DATETIME NOT NULL DEFAULT NOW(),
    DATE_UPDATED DATETIME NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    ID_IMAGE_RESOURCE INTEGER NOT NULL 
);

CREATE TABLE SESSIONS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DATE DATETIME NOT NULL DEFAULT NOW(),
    DEVICE VARCHAR(50) NOT NULL,
    IP VARCHAR(15) NOT NULL,
    COORDENATE POINT 
    ID_USER INTEGER
);

CREATE TABLE POSTS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_USER_POSTER INTEGER NOT NULL,
    ID_USER_CLOSER INTEGER,
    DESCRIPTION TEXT NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    DATE_CREATED DATETIME NOT NULL DEFAULT NOW(),
    DATE_CLOSED DATETIME,
    PRICE DECIMAL(6,2) NOT NULL
);

CREATE TABLE LIKES (
    ID_USER INTEGER NOT NULL,
    ID_POST INTEGER NOT NULL,
    DATE DATETIME NOT NULL DEFAULT NOW()
);

CREATE TABLE VIEWS (
    ID_USER INTEGER NOT NULL,
    ID_POST INTEGER NOT NULL,
    DATE DATETIME NOT NULL DEFAULT NOW()
);

CREATE TABLE POKEMONS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NUM_POKEDEX INTEGER,
    NAME VARCHAR(100) NOT NULL,
    TYPE VARCHAR(15) NOT NULL,
    TYPE2 VARCHAR(15),
    ID_IMAGE_RESOURCE INTEGER NOT NULL
);

CREATE TABLE IMAGE_RESOURCES (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    PATH VARCHAR(255) NOT NULL
);

CREATE TABLE OFFERS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_POKEMON INTEGER NOT NULL,
    ID_POST INTEGER NOT NULL,
    FORM VARCHAR(25) NOT NULL,
    SHINY BOOLEAN NOT NULL,
    PLACE_LOCATED POINT,
    PC INTEGER(5) NOT NULL
);

CREATE TABLE DEMANDS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_POKEMON INTEGER NOT NULL,
    ID_POST INTEGER NOT NULL,
    FORM VARCHAR(25) NOT NULL,
    SHINY BOOLEAN NOT NULL,
    PLACE_LOCATED POINT,
    PC INTEGER(5) NOT NULL
);

ALTER TABLE USERS ADD FOREIGN KEY (ID_IMAGE_RESOURCE) REFERENCES IMAGE_RESOURCES(ID);
ALTER TABLE POKEMONS ADD FOREIGN KEY (ID_IMAGE_RESOURCE) REFERENCES IMAGE_RESOURCES(ID);

ALTER TABLE SESSION ADD FOREIGN KEY (ID_USER) REFERENCES USER(ID);

ALTER TABLE POSTS ADD FOREIGN KEY (ID_USER_POSTER) REFERENCES USER(ID);
ALTER TABLE POSTS ADD FOREIGN KEY (ID_USER_CLOSER) REFERENCES USER(ID);

ALTER TABLE LIKES ADD FOREIGN KEY (ID_USER) REFERENCES USER(ID);
ALTER TABLE LIKES ADD FOREIGN KEY (ID_POST) REFERENCES POST(ID);

ALTER TABLE VIEWS ADD FOREIGN KEY (ID_USER) REFERENCES USER(ID);
ALTER TABLE VIEWS ADD FOREIGN KEY (ID_POST) REFERENCES POST(ID);

ALTER TABLE OFFERS ADD FOREIGN KEY (ID_POKEMON) REFERENCES POKEMONS(ID);
ALTER TABLE OFFERS ADD FOREIGN KEY (ID_POST) REFERENCES POST(ID);

ALTER TABLE DEMANDS ADD FOREIGN KEY (ID_POKEMON) REFERENCES POKEMONS(ID);
ALTER TABLE DEMANDS ADD FOREIGN KEY (ID_POST) REFERENCES POST(ID);